### ISSUE TITLE
FluxDiagram DimensionMismatch

### ISSUE THREAD

**Issue by laubapires** [ReactionMechanismGenerator/ReactionMechanismSimulator.jl#140]
Hi guys, hope you all are doing well!

I'm an RMG user but have just started using RMS. As a starter example, I was trying to do the same as Matt Johnson for the [Propane Oxidation](https://youtu.be/xCYDsnKnV_0) case. And everything went smoothly, but the getfluxdiagram function. I'm getting this error (the txt attached is showing the full out message): 
JULIA: DimensionMismatch("arrays could not be broadcast to a common size; got a dimension with lengths 63 and 1112")

As I don't know how to figure out this, I decided to make this question here. What should I be looking for in order to solve the issue? 
[ErrorFluxDiagram.txt](https://github.com/ReactionMechanismGenerator/ReactionMechanismSimulator.jl/files/6566483/ErrorFluxDiagram.txt)

**Comment by mjohnson541** [comment]
Thanks! I don't think this bug should exist on the latest release v3.2.0. I should have it fixed soon on master. You should be able to switch to v3.2.0 on pyrms by: 
1) activate the enivronment (rmg_env)
2) Enter the julia repl by running: `julia`
3) Run `]add ReactionMechanismSimulator@3.2.0` (`]` moves you into julia's package repl)
4) Click delete (to leave the julia Pkg repl and return to the julia repl)
5) Run `using ReactionMechanismSimulator` (does some preliminary compiling)
6) Run `exit()` to leave the julia repl
