### ISSUE TITLE
RMS not using downgraded version of StochasticDiffEq

### ISSUE THREAD

**Issue by sevyharris** [ReactionMechanismGenerator/ReactionMechanismSimulator.jl#175]
I'm trying to set up RMG-tests to use Github Actions, which requires adding RMS to a blank Ubuntu machine.

Apparently there's some bug or incompatibility with the latest StochasticDiffEq version, so I've been trying to use 6.36.0 with the following command:
`julia -e 'using Pkg; Pkg.add(PackageSpec(name="StochasticDiffEq",version="6.36.0")); Pkg.instantiate();'`

However, when I try to install RMS in the next line 
`julia -e 'using Pkg; Pkg.add(PackageSpec(name="ReactionMechanismSimulator",version="0.4")); using ReactionMechanismSimulator;'`

It defaults back to StochasticDiffEq v6.37.3 and fails to install.

The Github Actions log where the install fails is [here](https://github.com/ReactionMechanismGenerator/RMG-tests/runs/3939919918?check_suite_focus=true).

The RMG-tests code to install the julia packages is around line 110 of [install.sh](https://github.com/ReactionMechanismGenerator/RMG-tests/blob/switch_to_github_actions/install.sh).
The latest iteration looks something like this:

`julia -e 'using Pkg; Pkg.add(PackageSpec(name="StochasticDiffEq",version="6.36.0")); Pkg.instantiate();'`
`python -c "import julia; julia.install(); import diffeqpy; diffeqpy.install()"`
`julia -e 'using Pkg; Pkg.add(PackageSpec(name="ReactionMechanismSimulator",version="0.4")); using ReactionMechanismSimulator;'`
`ln -sfn $(which python-jl) $(which python)`

I might be using the wrong order of commands. I don't really know what this section does, I just copied it from step 6 of the [RMG Install instructions](https://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/anacondaDeveloper.html) and have been trying somewhat random and uninformed modifications. Any advice or help here would be appreciated, thanks!

**Comment by mjohnson541** [comment]
Hmm I think add doesn't compile by itself so you can stick the Pkg.add(PackageSpec(name="StochasticDiffEq",version="6.36.0")); line in between the add and using commands for ReactionMechanismSimulator. 

I would've thought you'd be able to leave out Pkg.instantiate() here. 

Also I'd recommend using RMS main:  
Pkg.add(PackageSpec(name="ReactionMechanismSimulator", rev="main"))

**Comment by sevyharris** [comment]
> Hmm I think add doesn't compile by itself so you can stick the Pkg.add(PackageSpec(name="StochasticDiffEq",version="6.36.0")); line in between the add and using commands for ReactionMechanismSimulator.
> 
> I would've thought you'd be able to leave out Pkg.instantiate() here.
> 
> Also I'd recommend using RMS main: Pkg.add(PackageSpec(name="ReactionMechanismSimulator", rev="main"))

Thanks! I'll give those suggestions a try
