### ISSUE TITLE
No sensitivity for interface reactions

### ISSUE THREAD

**Issue by ChrisBNEU** [ReactionMechanismGenerator/ReactionMechanismSimulator.jl#223]
This may be user error, or just a fundamental misunderstanding, but when doing transitory sensitivities (trapezoidal and normalized), I find that all of the sensitivities for the interface reactions are 0. I have attached an example using the Gas-Catalyst Interface notebook. 

if you look at the sensitivities returned by `transitorysensitivitiesfulltrapezoidal`, all of the sensitivities for CH4 are either the gas phase or surface phase. there are no adsorption/desorption reactions, no matter what time you choose.

top 20 at t=1e-6s
<img width="753" alt="image" src="https://github.com/ReactionMechanismGenerator/ReactionMechanismSimulator.jl/assets/56306881/28789faf-e908-493f-8938-59191d264ee6">

top 20 at t=0.1s
<img width="806" alt="image" src="https://github.com/ReactionMechanismGenerator/ReactionMechanismSimulator.jl/assets/56306881/d90bc886-8ca4-4d35-a2db-add1e8d8d297">

but if I specifically look at all of the adsorption/desorption reactions for CH4, the values are all 0. 
<img width="790" alt="image" src="https://github.com/ReactionMechanismGenerator/ReactionMechanismSimulator.jl/assets/56306881/acdfc94e-5804-4050-9340-c0c305d54fa0">

I thought maybe it was because I was normalizing, but I ran into another issue when I set `normalized=false`. it looks like the `transitorysensitivitiesfulltrapezoidal` function is only set up for the `Simulation` object, and not the `SystemSimulation` object, so I get the error 'type SystemSimulation has no field domain'. 
[Gas-Catalyst Interface.ipynb.zip](https://github.com/ReactionMechanismGenerator/ReactionMechanismSimulator.jl/files/11918431/Gas-Catalyst.Interface.ipynb.zip)

**Comment by mjohnson541** [comment]
It looks like we are only normalizing out the rate coefficients associated with Domains, when we should be doing this for interfaces as well here: https://github.com/ReactionMechanismGenerator/ReactionMechanismSimulator.jl/blob/cb70323672becaf48a367172305f017809b72c55/src/TransitorySensitivities.jl#L160 and likely in other locations in that file as well.

**Comment by ChrisBNEU** [comment]
I wasn't sure if I should comment this on the pr or the issue, but here seemed more appropriate. 

If I calculate the transitory sensitivity explicitly, and try to find any nonzero components of dSdt for parameter indices corresponding to the surface reactions, I get all 0s. I tried this at a number of times (1e-20, 1e-10, 1e-5, 1e-1), but it always returns a matrix that's all 0s. 

<img width="998" alt="image" src="https://github.com/ReactionMechanismGenerator/ReactionMechanismSimulator.jl/assets/56306881/2fb5ee15-9251-45f2-82a1-d174307855c9">

I'd expect some of these values to be non-zero, especially at earlier times when it is mostly adsorption reactions taking place.
<img width="610" alt="image" src="https://github.com/ReactionMechanismGenerator/ReactionMechanismSimulator.jl/assets/56306881/19805fe4-0d28-4f05-9839-53375ca41754">
<img width="553" alt="image" src="https://github.com/ReactionMechanismGenerator/ReactionMechanismSimulator.jl/assets/56306881/93c31eea-18f4-4eb4-8efa-b91d0d9e54f1">

Any ideas on why that might be? I am a little stuck. If I look at the parameter jacobian it is the same, unsurprisingly. Perhaps I am just fundamentally misunderstanding how the jacobian matrix is calculated.

**Comment by ChrisBNEU** [comment]
would I give it the same args as `Jacobianp`? because it's giving me an error `MethodError: no method matching jacobianpforwarddiff!(<long nested list of data types used>)` when I do that. Apologies, but I don't really know my way around julia that well, and there aren't really any examples using `jacobianpforwarddiff!` for a SystemSimulation. `jacobianp` I was able to copy code from the plotting functions.

**Comment by mjohnson541** [comment]
No, the arguments are different, I believe the dispatch you want is here: https://github.com/ReactionMechanismGenerator/ReactionMechanismSimulator.jl/blob/cb70323672becaf48a367172305f017809b72c55/src/Reactor.jl#L811

**Comment by mjohnson541** [comment]
You'll need to make an empty Jacobian matrix to feed into it.

**Comment by ChrisBNEU** [comment]
not sure if I did this correctly, but I am getting that those columns are also all 0: 
<img width="622" alt="image" src="https://github.com/ReactionMechanismGenerator/ReactionMechanismSimulator.jl/assets/56306881/fd7f8b7c-7dfe-434f-af2a-3fa4f3436ebd">
