### ISSUE TITLE
What need to do if we want to remove dependence of Python?

### ISSUE THREAD

**Issue by jiweiqi** [ReactionMechanismGenerator/ReactionMechanismSimulator.jl#26]
I am thinking of removing Python dependence to make the installation more smooth. I am trying to look into the code to figure out what need to do and what's the consequence.

**Comment by mjohnson541** [comment]
So currently python is used for: parsing Chemkin files, drawing molecular structures, drawing flux diagrams, determining element and radical content from smiles/inchi, writing and reading yaml files.  

I haven't been able to find a Julia package that can do all of these things and PyCall makes it super easy to call stuff within the code. 

I've been spending a lot of time recently trying to build conda packages for RMS and pyrms to make the install super easy and I've gotten a lot of it working, but it isn't quite there yet. 

I think the current primary issue is that I haven't updated the pyimport_conda statements yet to reflect rmg's python 3 environment so currently PyCall usually fails to automatically install all the python dependencies. However, you can just create a conda env and install with `conda install -c defaults -c rmg -c rdkit -c cantera -c pytorch -c conda-forge rmg=3.0.0` and I'm pretty sure that will install all of the dependencies needed.
