### ISSUE TITLE
Do I need to learn RMG in order to run the simulation?

### ISSUE THREAD

**Issue by jiweiqi** [ReactionMechanismGenerator/ReactionMechanismSimulator.jl#27]
I have no experience with RMG. If I only want to simulate ignition process from a Chemkin or Cantera mechanism. Do I need to learn any knowledge about RMG? Or I can just read the Chemkin mechanism using the parse module?

**Comment by xiaoruiDong** [comment]
In my opinion, you can easily use RMS without the experience of RMG. Unless you try to develop RMS, you won't touch any RMG dependencies.
