### ISSUE TITLE
Adjoint Sensitivities for Multiple Domains

### ISSUE THREAD

**Issue by mjohnson541** [ReactionMechanismGenerator/ReactionMechanismSimulator.jl#85]
When I attempted to write adjoint sensitiviites for multiple domains I ran into #84 and another distinct issue with ConstantTPDomain. I had difficulty decoupling these issues so I think it's best to wait to resolve this until #84 is dealt with. The work I started on this is available on the `multidomainsens` branch.

**Comment by hwpang** [comment]
I plan to work on this if it's not taken yet!

**Comment by mjohnson541** [comment]
That would be fantastic!

**Comment by hwpang** [comment]
I think this issue is resolved with PR #170 being merged, so I will close this issue.
